"""Deployment configuration generators for PyWire apps."""

from pathlib import Path

DOCKERFILE_TEMPLATE = """\
FROM python:3.12-slim
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY . .

# Session timeout in seconds (default: 1800 = 30 min)
ENV SESSION_TTL=1800

EXPOSE 8000
CMD ["uv", "run", "pywire", "run", "--host", "0.0.0.0", "--port", "8000", "--workers", "{workers}"]
"""

RENDER_YAML_TEMPLATE = """\
services:
  - type: web
    name: {project_name}
    runtime: docker
    plan: free
    envVars:
      - key: SESSION_TTL
        value: "1800"  # Session timeout in seconds (default: 30 min)
"""

RENDER_YAML_REDIS_TEMPLATE = """\
services:
  - type: web
    name: {project_name}
    runtime: docker
    plan: starter
    envVars:
      - key: REDIS_URL
        fromService:
          name: {project_name}-kv
          type: keyvalue
          property: connectionString
      - key: SESSION_TTL
        value: "1800"  # Session timeout in seconds (default: 30 min)

  - type: keyvalue
    name: {project_name}-kv
    plan: starter
    ipAllowList: []
"""

FLY_TOML_TEMPLATE = """\
app = "{app_name}"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true

[env]
  # Session timeout in seconds (default: 1800 = 30 min)
  SESSION_TTL = "1800"

[[vm]]
  memory = "512mb"
  cpus = 1
"""

RAILWAY_JSON_TEMPLATE = """\
{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "dockerfilePath": "Dockerfile"
  }
}
"""

WRANGLER_TOML_TEMPLATE = """\
name = "{project_name}"
main = "entry.py"
compatibility_date = "2025-01-01"
compatibility_flags = ["python_workers"]

[assets]
directory = "./.pywire/deploy/public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "PYWIRE_SESSION"
class_name = "PyWireSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PyWireSessionDO"]
"""

CF_ENTRY_TEMPLATE = """\
import asgi
from pywire_do import PyWireSessionDO, _load_app
from workers import WorkerEntrypoint
from js import URL
import uuid


class Default(WorkerEntrypoint):
    async def on_fetch(self, request):
        app = _load_app()
        url = URL.new(request.url)
        upgrade = (request.headers.get("Upgrade") or "").lower()

        if upgrade == "websocket":
            session_id = url.searchParams.get("session") or str(uuid.uuid4())
            stub = self.env.PYWIRE_SESSION.getByName(session_id)
            return await stub.fetch(request)

        return await asgi.fetch(app, request.js_object, self.env)
"""

CF_DURABLE_OBJECT_TEMPLATE = """\
\"\"\"PyWire Durable Object — session actor with WebSocket hibernation.

This module is generated by `pywire build --platform cloudflare`.
Uses shared pywire.runtime modules for protocol + page resolution.

Imports are deferred to first request to stay within Cloudflare Workers'
startup CPU limit. Only the Cloudflare SDK bindings are loaded at startup.
\"\"\"

from workers import DurableObject, Response
from js import WebSocketPair

_app_instance = None


def _load_app():
    \"\"\"Lazy-load the PyWire app and register routes on first call.\"\"\"
    global _app_instance
    if _app_instance is not None:
        return _app_instance
    from {app_module} import {app_attr}
    import _routes  # noqa: F401 — registers routes as a side effect
    _app_instance = {app_attr}
    return _app_instance


def _send(ws, msg):
    import msgpack
    from pyodide.ffi import to_js
    ws.send(to_js(msgpack.packb(msg)))


def _send_update(ws, update):
    from pywire.runtime.protocol import build_update_payload
    _send(ws, build_update_payload(update))


def _decode(message):
    try:
        import msgpack
        if isinstance(message, (bytes, bytearray, memoryview)):
            return msgpack.unpackb(message, raw=False)
        if hasattr(message, "to_py"):
            return msgpack.unpackb(bytes(message.to_py()), raw=False)
        return {{}}
    except Exception:
        return {{}}


def _resolve_page(path):
    from pywire.runtime.page_resolver import resolve_page
    app = _load_app()
    result = resolve_page(app.router, path)
    if result is None:
        return None
    page, _params, _variant_name = result
    return page


class PyWireSessionDO(DurableObject):
    def __init__(self, state, env):
        super().__init__(state, env)
        self.ctx = state
        self.page = None

    async def on_fetch(self, request):
        _load_app()  # ensure app + routes ready before handling
        upgrade = (request.headers.get("Upgrade") or "").lower()
        if upgrade == "websocket":
            pair = WebSocketPair.new()
            client, server = pair.object_values()
            self.ctx.acceptWebSocket(server)
            return Response(None, status=101, web_socket=client)
        return Response("OK", headers={{"Content-Type": "text/plain"}})

    async def on_webSocketMessage(self, ws, message):
        msg = _decode(message)
        msg_type = msg.get("type", "")
        try:
            if msg_type == "init":
                await self._handle_init(ws, msg)
            elif msg_type == "event":
                await self._handle_event(ws, msg)
            elif msg_type == "relocate":
                await self._handle_relocate(ws, msg)
            elif msg_type == "pong":
                pass
        except Exception as e:
            import traceback
            traceback.print_exc()
            _send(ws, {{"type": "error", "error": str(e)}})

    async def on_webSocketClose(self, ws, code, reason, was_clean):
        if self.page:
            await self._persist_state()
        ws.close(code, reason)

    async def _restore_from_storage(self, page):
        snapshot = await self.ctx.storage.get("page_state")
        if snapshot:
            try:
                state = snapshot.to_py() if hasattr(snapshot, "to_py") else snapshot
                from pywire.runtime.session_serializer import restore_page_state
                restore_page_state(page, state)
                return True
            except Exception:
                pass
        return False

    def _setup_broadcaster(self, ws, page):
        async def broadcast_update():
            update = await page.render_update(init=False)
            _send_update(ws, update)
        page._on_update = broadcast_update

    async def _handle_init(self, ws, msg):
        path = msg.get("path", "/")
        self.page = _resolve_page(path)
        if not self.page:
            _send(ws, {{"type": "error", "error": "Not Found"}})
            return

        session_restored = await self._restore_from_storage(self.page)
        self._setup_broadcaster(ws, self.page)
        await self.page.render(init=True)

        if self.page._pending_navigation:
            _send(ws, {{"type": "navigate", "path": self.page._pending_navigation}})
            self.page._pending_navigation = None
            return

        _send(ws, {{
            "type": "init_ack",
            "session_id": "",
            "session_restored": session_restored,
        }})
        await self.page._run_hooks(self.page.MOUNT_HOOKS)
        await self._persist_state()

    async def _handle_event(self, ws, msg):
        handler_name = msg.get("handler")
        event_data = msg.get("data", {{}})

        if not self.page:
            self.page = _resolve_page(msg.get("path", "/"))
            if not self.page:
                _send(ws, {{"type": "error", "error": "No page"}})
                return
            await self._restore_from_storage(self.page)
            await self.page.render(init=True)

        self._setup_broadcaster(ws, self.page)

        if handler_name:
            update = await self.page.handle_event(handler_name, event_data)
        else:
            update = await self.page.render_update(init=False)

        if self.page._pending_navigation:
            _send(ws, {{"type": "navigate", "path": self.page._pending_navigation}})
            self.page._pending_navigation = None
            return

        _send_update(ws, update)
        await self.page._run_hooks(self.page.AFTER_UPDATE_HOOKS)
        await self._persist_state()

    async def _handle_relocate(self, ws, msg):
        path = msg.get("path", "/")
        old_page = self.page

        self.page = _resolve_page(path)
        if not self.page:
            _send(ws, {{"type": "reload"}})
            return

        if old_page:
            self.page.user = getattr(old_page, "user", None)

        self._setup_broadcaster(ws, self.page)
        response = await self.page.render(init=False)
        html = response.body.decode("utf-8") if isinstance(response.body, bytes) else response.body
        _send(ws, {{"type": "update", "html": html}})
        await self.page._run_hooks(self.page.MOUNT_HOOKS)
        await self._persist_state()

    async def _persist_state(self):
        if not self.page:
            return
        try:
            from pywire.runtime.session_serializer import snapshot_page_state
            from pyodide.ffi import to_js
            snapshot = snapshot_page_state(self.page)
            await self.ctx.storage.put("page_state", to_js(snapshot))
        except Exception:
            pass
"""


def generate_dockerfile(project_root: Path, workers: int = 1) -> str:
    """Generate Dockerfile content for a PyWire project."""
    return DOCKERFILE_TEMPLATE.format(workers=workers)


def generate_render_yaml(
    project_root: Path, project_name: str, redis: bool = False
) -> str:
    """Generate render.yaml content for a PyWire project."""
    if redis:
        return RENDER_YAML_REDIS_TEMPLATE.format(project_name=project_name)
    return RENDER_YAML_TEMPLATE.format(project_name=project_name)


def generate_fly_toml(project_root: Path, project_name: str) -> str:
    """Generate fly.toml content for a PyWire project."""
    return FLY_TOML_TEMPLATE.format(app_name=project_name)


def generate_railway_json(project_root: Path) -> str:
    """Generate railway.json content for a PyWire project."""
    return RAILWAY_JSON_TEMPLATE


def generate_wrangler_toml(
    project_root: Path,
    project_name: str,
) -> str:
    """Generate wrangler.toml content for Cloudflare Workers with Durable Objects."""
    return WRANGLER_TOML_TEMPLATE.format(project_name=project_name)


def _parse_app_string(app_string: str) -> tuple[str, str]:
    """Parse 'src.main:app' into ('src.main', 'app')."""
    if ":" in app_string:
        app_module, app_attr = app_string.rsplit(":", 1)
    else:
        app_module, app_attr = app_string, "app"
    return app_module, app_attr


def generate_cf_entry(project_root: Path, app_string: str = "main:app") -> str:
    """Generate entry.py for Cloudflare Workers with Durable Object routing."""
    app_module, app_attr = _parse_app_string(app_string)
    return CF_ENTRY_TEMPLATE.format(app_module=app_module, app_attr=app_attr)


def generate_cf_durable_object(project_root: Path, app_string: str = "main:app") -> str:
    """Generate pywire_do.py — the Durable Object class for PyWire sessions."""
    app_module, app_attr = _parse_app_string(app_string)
    return CF_DURABLE_OBJECT_TEMPLATE.format(app_module=app_module, app_attr=app_attr)


def validate_deploy_config(platform: str, project_root: Path) -> list[str]:
    """Check what's missing for deployment on the given platform.

    Returns a list of warning/error messages. An empty list means
    everything looks good.
    """
    issues: list[str] = []

    if not (project_root / "pyproject.toml").exists():
        issues.append("Missing pyproject.toml — required for dependency installation.")

    if (
        platform in ("docker", "fly", "render", "railway")
        and not (project_root / "uv.lock").exists()
    ):
        issues.append(
            "Missing uv.lock — run 'uv lock' to generate a lock file for reproducible builds."
        )

    return issues
