"""Post-render HTML injection for CSRF tokens.

Three injections, all string-level (no DOM parser):

1. ``<meta name="pywire-csrf-token" content="...">`` and a JS global
   ``window.__PYWIRE_CSRF_TOKEN__`` are placed inside ``<head>`` so AJAX
   clients can read the token without consulting a form.
2. A hidden ``<input type="hidden" name="_csrf_token" value="...">`` is
   spliced into every ``<form>`` opening tag so plain HTML form POSTs
   submit the token alongside their fields.

Forms carrying ``data-pywire-no-csrf`` are skipped — that's the v0.1
opt-out signal until a proper ``!no_csrf`` page directive lands.

Raw-text spans (``<script>``, ``<style>``, ``<textarea>``, ``<title>``)
are excluded so user JS containing string literals like ``"<form>"`` or
``"</head>"`` does not trigger spurious injections. The exclusion helper
is reused from :mod:`pywire.runtime.page` to avoid drift.
"""

from __future__ import annotations

import re

from pywire.runtime.page import _raw_text_spans

_FORM_OPEN_RE = re.compile(r"<form\b[^>]*>", re.IGNORECASE | re.DOTALL)
_NO_CSRF_RE = re.compile(r"\bdata-pywire-no-csrf\b", re.IGNORECASE)
_HEAD_CLOSE_RE = re.compile(r"</head\s*>", re.IGNORECASE)
_BODY_OPEN_RE = re.compile(r"<body\b[^>]*>", re.IGNORECASE)


def inject_csrf_tokens(html: str, token: str) -> str:
    """Return ``html`` with CSRF token injections applied.

    Idempotent for already-present hidden inputs only via attribute
    inspection on each form tag — re-injecting into the full document
    will produce duplicate ``<meta>`` and JS-global tags. The framework
    only injects once per render so this is fine in practice.
    """
    if not token:
        return html

    safe = _attr_escape(token)
    raw_spans = _raw_text_spans(html)

    head_block = (
        f'<meta name="pywire-csrf-token" content="{safe}">'
        f'<script>window.__PYWIRE_CSRF_TOKEN__="{safe}";</script>'
    )

    head_match = _first_match_outside_raw(html, _HEAD_CLOSE_RE, raw_spans)
    if head_match is not None:
        head_idx = head_match.start()
        html = html[:head_idx] + head_block + html[head_idx:]
    else:
        body_match = _first_match_outside_raw(html, _BODY_OPEN_RE, raw_spans)
        if body_match is not None:
            insert_at = body_match.end()
            html = html[:insert_at] + head_block + html[insert_at:]
        else:
            html = head_block + html

    raw_spans = _raw_text_spans(html)
    hidden_input = f'<input type="hidden" name="_csrf_token" value="{safe}">'

    matches = [
        m
        for m in _FORM_OPEN_RE.finditer(html)
        if not _is_in_spans(m.start(), raw_spans) and not _NO_CSRF_RE.search(m.group(0))
    ]
    for m in reversed(matches):
        insert_at = m.end()
        html = html[:insert_at] + hidden_input + html[insert_at:]

    return html


def _is_in_spans(idx: int, spans: list[tuple[int, int]]) -> bool:
    for start, end in spans:
        if start <= idx < end:
            return True
    return False


def _first_match_outside_raw(
    html: str, pattern: "re.Pattern[str]", spans: list[tuple[int, int]]
) -> "re.Match[str] | None":
    for m in pattern.finditer(html):
        if not _is_in_spans(m.start(), spans):
            return m
    return None


def _attr_escape(value: str) -> str:
    """Escape characters that would break out of an HTML attribute value.

    CSRF tokens generated by :mod:`pywire_secure.csrf` are hex digits and
    a single colon — no escaping is strictly needed today. Defensive
    escaping keeps the contract clean if the token format ever widens or
    a custom strategy emits richer values.
    """
    return (
        value.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
