#!/bin/sh -e

echo "=== Checking Tree-sitter Grammar ==="
(cd packages/tree-sitter-pywire && ./scripts/check)

echo "=== Checking PyWire Parser ==="
(cd packages/pywire-parser && ./scripts/check)

echo "=== Checking PyWire (Core, Client) ==="
(cd packages/pywire && ./scripts/check)

echo "=== Checking PyWire Templates ==="
(cd packages/pywire-templates && ./scripts/check)

echo "=== Checking PyWire CLI ==="
(cd packages/pywire-cli && ./scripts/check)

echo "=== Checking PyWire Auth ==="
(cd packages/pywire-auth && ./scripts/check)

echo "=== Checking PyWire Language Server ==="
(cd packages/pywire-language-server && ./scripts/check)

echo "=== Checking Create PyWire App ==="
(cd packages/create-pywire-app && ./scripts/check)

echo "=== Checking Examples ==="
(cd examples && ./scripts/check)

echo "=== Checking VS Code Extension ==="
(cd packages/vscode-pywire && ./scripts/check)

echo "=== Checking Prettier Plugin PyWire ==="
(cd packages/prettier-plugin-pywire && ./scripts/check)

echo "=== Checking PyWire Docs ==="
(cd docs && pnpm check)
