#!/bin/sh -e
# Lint core, client, and docs
export SOURCE_FILES="src/pywire"

set -x

uv run --with ruff ruff format $SOURCE_FILES
uv run --with ruff ruff check --fix $SOURCE_FILES

echo "-> Linting client..."
if [ -d "src/pywire/client" ]; then
    (
        cd src/pywire/client
        if [ ! -x node_modules/.bin/eslint ]; then
            pnpm install
        fi
        pnpm format
        pnpm lint:fix
    )
fi

echo "-> Linting docs..."
if [ -d "docs" ]; then
    (
        cd docs
        if [ ! -x node_modules/.bin/prettier ]; then
            pnpm install --prefer-frozen-lockfile
        fi
        pnpm format
        pnpm lint:fix
    )
fi