name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      - "docs-*"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'nightly'
        type: choice
        options:
          - nightly
          - production

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Documentation
    steps:
      - name: Checkout pywire
        uses: actions/checkout@v4
        with:
          path: pywire
          fetch-depth: 0

      - name: Checkout tree-sitter-pywire
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/tree-sitter-pywire
          path: tree-sitter-pywire
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-emscripten

      - name: Setup Emscripten 3.1.58
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.58
          actions-cache-folder: 'emsdk-cache'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        working-directory: pywire
        run: |
          cd docs
          pnpm install

      - name: Build
        working-directory: pywire
        env:
          PYWIRE_WASM_BUILD: "1"
          CARGO_TARGET_WASM32_UNKNOWN_EMSCRIPTEN_RUSTFLAGS: "-C target-feature=-bulk-memory -C link-arg=-sWASM_OPT=0"
          EMCC_SKIP_WASM_OPT: "1"
        run: |
          cd docs
          pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pywire-docs
          directory: pywire/docs/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ (github.event.inputs.environment == 'production' || startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/docs-')) && 'main' || 'nightly' }}

