name: Prettier Plugin PyWire

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier-plugin-pywire:
    name: 'Prettier Plugin PyWire'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: ./scripts/check

      - name: Run coverage
        run: ./scripts/coverage
